### ISSUE TITLE
Undefined index in custom menu

### ISSUE THREAD

**Issue by glueckpress** [nullx27/Splitdown#12]
When adding a menu item to a custom menu I get these undefined indexes: 

> Notice: Undefined index: splitdown-markdown in /…/Splitdown/Splitdown.php on line 92
> Notice: Undefined index: content in /…/Splitdown/Splitdown.php on line 93

**Comment by chrisjhoughton** [comment]
Should be fixed in https://github.com/Necrotex/Splitdown/pull/18
