### ISSUE TITLE
Splitdown causes server execution timeout on post save/publish/update

### ISSUE THREAD

**Issue by Dakta** [nullx27/Splitdown#20]
I'd love to use Splitdown, but when I have the plugin activated every single time I click "Update/Save/Publish" on post.php it hangs. Splitdown correctly parses the output and saves the post content, but other plugins like Yoast's SEO don't get their options saves and the post.php page never completes execution This is WP 3.8.1. I've had it simply fail silently (white screen, no returned result), return a memory exceeded error, return an execution time exceeded error... Plenty of bugs across an array of WordPress systems including in post.php:629 and cache.php:455

I don't know if it's a Splitdown bug, or a conflict with another plugin (I have a number of common ones including ACF and Yoast's WordPress SEO). I can manually test for conflicts with all installed plugins, if necessary, just haven't done it yet.

I'll try to shed more light on this issue myself, but I'd appreciate the input of someone who knows the plugin's architecture.

**Comment by Dakta** [comment]
OK, I just checked by deactivating all other plugins and it seems that Splitdown is the sole source. I'm guessing it's here: https://github.com/Necrotex/Splitdown/blob/master/Splitdown.php#L112

**Comment by Dakta** [comment]
Some quick-'n-dirty debugging has revealed that `save()` is causing an infinite loop, despite the `remove_action()`-`add_action()` calls. I even cleared out all previous uses of `__CLASS__` in favor of `$this`, as used elsewhere, to no avail.

**Comment by chrisjhoughton** [comment]
Hi Dakta, I can confirm this is a Splitdown bug, fixed in https://github.com/Necrotex/Splitdown/commit/10960b138699f67cd2a6543f37122561eb68d93d. 

`$this` was being used on the `save` function, resulting in an infinite loop. Re-update it should be fixed now. Any more issues let me know!

**Comment by Dakta** [comment]
Can confirm bug is no longer present. Any idea why using `$this` as opposed to `__CLASS__` caused a loop? Was it referring to the wrong instance of the class, so the `add_action()`/`remove_action()` calls designed to avoid this kind of loop weren't actually doing anything?
