### ISSUE TITLE
Bestehende Beiträge 

### ISSUE THREAD

**Issue by bueltge** [nullx27/Splitdown#4]
fehlt der Inhalt, siehe Screenshot.
Wenn man bestehende Artikel bearbeitet, dann ist der Editor leer, Vorschau passt.

![auswahl_001](https://f.cloud.github.com/assets/133425/1701080/348509fe-603f-11e3-82f2-3f827ef3a1c2.png)

**Comment by nullx27** [comment]
fixed with 1f5b88e3773015c755cf22959f34c52300c6f935

At the moment the markdown gets converted clientside. This gets triggerd when the the editor but not the preview is empty. So its get only saved when you update the post.

**Comment by bueltge** [comment]
great, but I have to test later.
